@startuml 6-5

state 電源SW_OFF{
  [*] --> 電源SW_OFF
  電源SW_ON --> 右旋回 : 電源SWがON
}

state 右旋回 {
  光センサーが明るい --> 左旋回 
  光センサーが暗い --> 右旋回 
  ラインの右境界線上を進む --> 右旋回
}

state 左旋回 {
  光センサーが暗い --> 左旋回 
  光センサーが明るい --> 右旋回 
  ラインの右境界線上を進む --> 左旋回
  電源SW_OFF --> 電源SW_OFF : 電源SWがOFF
}

@enduml
