
@startuml 演習3-6_OBJ_資格取得のオブジェクト図

object 高橋洋平 {
  資格情報
}

object 樋口正之 {
  資格情報
}

object 情報処理安全確保支援士 {
  試験名 = "情報処理安全確保支援士"
  取得日 = "2020/10/21"
}

object LinuC_Level1 {
  試験名 = "LinuC_Level1"
  取得日 = "2021/03/28"
}

高橋洋平 -> 情報処理安全確保支援士 : 申請
高橋洋平 -> LinuC_Level1 : 申請
樋口正之 -> 情報処理安全確保支援士

@enduml
