@startuml 6-5

left to right direction

actor ユーザー as User


rectangle システム {
  User --> (ユースケース)

  (ユースケース) --> (ライントレーサー) : ライントレース

  (ユースケース) --> (ライントレーサー) : 電源ON
  (ユースケース) --> (ライントレーサー) : 電源OFF
}

(ライントレーサー) --> (ラインセンサー)
(ライントレーサー) --> (モータ)
(ライントレーサー) --> (CPU)
(ライントレーサー) --> (電源SW)

@enduml
