@startuml 演習3-5_OBJホテル宿泊予約
object 301号室 {
  - タイプ = "シングル"
  - 宿泊費 = 11000
  - キャンペーン価格 = 9000
}
object 302号室 {
  - タイプ = "シングル"
  - 宿泊費 = 11000
  - キャンペーン価格 = 9000
}
object 303号室 {
  - タイプ = "シングル"
  - 宿泊費 = 11000
  - キャンペーン価格 = 9000
}
object Aさん {
  - 名前 = "Aさん"
  - チェックイン日 = "5月3日"
  - 宿泊泊数 = 2
}
object Bさん {
  - 名前 = "Bさん"
  - チェックイン日 = "5月3日"
  - 宿泊泊数 = 2
}
Aさん *-- 301号室 : 宿泊する
Bさん *-- 303号室 : 宿泊する
@enduml
