@startuml 2-4
'left to right direction

actor ユーザー as user

rectangle 予約システム {
  user --> (予約する)

  (予約する) ..> (支払い) : <<include>>
  
  (予約する) ..> (キャンペーン価格で予約する) : <<extend>>
  
  (支払い) --> (支払い完了)
  (支払い完了) --> (予約完了)
  
  (キャンペーン価格で予約する) --> (キャンペーン情報を確認する)
}

rectangle キャンペーンシステム {
  (キャンペーン情報を確認する) <-- キャンペーンシステム : <<uses>>
}

@enduml

