@startuml 6-3
[*] --> メニュー画面

メニュー画面 --> 予約と確認画面 : 予約をする
予約と確認画面 --> あなたの順番画面 : 登録ボタンを押す
予約と確認画面 --> あなたの順番画面 : 確認ボタンを押す
予約と確認画面 --> メニュー画面 : 取消ボタンを押す
あなたの順番画面 --> メニュー画面 : メニューに戻る
あなたの順番画面 --> 今の順番画面 : 患者番号更新
今の順番画面 --> メニュー画面 : メニューに戻る

@enduml
